#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/urt42_engine.png
	update-icon-caches /usr/share/icons/urt42_server.png
	update-icon-caches /usr/share/icons/urt42_update.png
fi
# End automatically added section
